runtime: nodejs18

env: standard

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65

handlers:
- url: /static
  static_dir: build/static
  secure: always

- url: /(.*\.(json|ico|js|txt))$
  static_files: build/\1
  upload: build/.*\.(json|ico|js|txt)$
  secure: always

- url: /.*
  static_files: build/index.html
  upload: build/index.html
  secure: always

env_variables:
  NODE_ENV: 'production'
